# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cW9IyvIDsNtr8Pb5dVyZZTqOuW1D0jz6
"""

def count_words(sentence):
    words = sentence.split()  # Split the sentence into words
    return len(words)  # Return the count of words

sentence = input("Enter a sentence: ")
word_count = count_words(sentence)
print("Word count:", word_count)